### ISSUE TITLE
Use lower-case function names

### ISSUE THREAD

**Issue by nalimilan** [seebk/PortAudio.jl#1]
I was just giving a quick look at the package, and I noticed that the functions `Pa_Initialize` and `Pa_Terminate` don't follow the standard Julia naming style. I'd suggest using all lower-case.

You could also call them `PortAudio.initialize` and `PortAudio.terminate` (i.e. do not export them). The same strategy could be used for `list_portaudio_devices`, giving `PortAudio.list_devices`.

My two cents, keep up the good work!

**Comment by seebk** [comment]
Thanks for that proposal, sounds like a good idea and I have just changed it in master.
